[package]
name = "_boilerplate"
version = "0.0.1"
edition = "2021"

[dependencies]
pyo3 = "0.27.1"

[lib]
# https://doc.rust-lang.org/cargo/reference/cargo-targets.html#library
name = "_boilerplate"
path = "src/lib.rs"
crate-type = ["cdylib"]
