[services.ec2]
operations = [
  'DescribeInstances',
  'DescribeVpcs',
  'RebootInstances',
  'RunInstances',
  'StartInstances',
  'StopInstances',
  'TerminateInstances',
]

[services.s3]
operations = [
  'DeleteObject',
  'GetObject',
  'ListBuckets',
  'ListObjectsV2',
  'PutObject',
]
