deps = [
  # packaging
  'apt-transport-https',
  'ca-certificates',
  'software-properties-common',

  # base system
  'dumb-init',
  'lsb-release',
  'sudo',

  # networking & network diagnostics
  'aria2',
  'bmon',
  'curl',
  'dnsutils',
  'iputils-ping',
  'iputils-tracepath',
  'mosh',
  'net-tools',
  'netcat-openbsd',
  'openssh-server',
  'socat',
  'tcpdump',
  'telnet',
  'wget',

  # build essentials & compilers
  'build-essential',
  'clang',
  'cmake',
  'g++',
  'g++-14',
  'gcc',
  'gcc-14',
  'llvm',
  'make',
  'pkg-config',

  # language toolchains & runtimes
  'nodejs',
  'npm',
  'perl',
  'ruby',

  # parsers, generators & compiler tooling
  'bison',
  'flex',
  'protobuf-compiler',
  'xsltproc',

  # version control systems
  'cvs',
  'git',
  'mercurial',
  'subversion',

  # debugging, tracing & profiling
  'gdb',
  'lsof',
  'strace',

  # data formats
  'jq',

  # databases
  'libdb-dev',
  'libpq-dev',
  'postgresql-client',

  # terminal UX & interactive tools
  'btop',
  'htop',
  'less',
  'moreutils',
  'ncdu',
  'ripgrep',
  'silversearcher-ag',
  'tmux',

  # shells
  'zsh',

  # editors & shells
  'emacs',
  'nano',
  'vim',

  # crypto, auth & trust
  'gnupg',
  'gnupg-agent',

  # documentation & introspection
  'file',
  'man-db',
  'graphviz',

  # chat & communication
  'irssi',

  # archiving & compression
  'zip',
  'unzip',
]
