[deps.httplib]
include = ['.']

[deps.httplib.git]
url = 'https://github.com/yhirose/cpp-httplib'
rev = 'a7bc00e3307fecdb4d67545e93be7b88cfb1e186'
subtrees = ['httplib.h']

[deps.httplib.cmake.fetch_content.git]
repository = 'https://github.com/yhirose/cpp-httplib.git'
tag = 'a7bc00e3307fecdb4d67545e93be7b88cfb1e186'


#

[deps.json]
include = ['single_include']

[deps.json.git]
url = 'https://github.com/nlohmann/json'
rev = '9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03'
subtrees = ['single_include']

[deps.json.cmake.fetch_content]
url = 'https://github.com/nlohmann/json/releases/download/v3.11.3/json.tar.xz'


#

[deps.pybind11]
include = ['include']

[deps.pybind11.git]
url = 'https://github.com/pybind/pybind11'
rev = '945e251a6ce7273058b36214d94415e9c9530b8e'
subtrees = ['include']


#

[deps.ut]
include = ['include']

[deps.ut.git]
url = 'https://github.com/boost-ext/ut'
rev = 'f83e15c7f1edb49b4ec20f866eec06940d18a47d'
subtrees = ['include']
