deps = [
  'build-essential',
  'gdb',
  'lcov',
  'libbz2-dev',
  'libffi-dev',
  'libgdbm-compat-dev',
  'libgdbm-dev',
  'liblzma-dev',
  'libncurses5-dev',
  'libreadline6-dev',
  'libsqlite3-dev',
  'libssl-dev',
  'lzma',
  'lzma-dev',
  'pkg-config',
  'tk-dev',
  'uuid-dev',
  'zlib1g-dev',
]
