deps = [
  'apt-transport-https',
  'aria2',
  'bison',
  'bmon',
  'btop',
  'build-essential',
  'ca-certificates',
  'clang',
  'cmake',
  'curl',
  'cvs',
  'dnsutils',
  'dumb-init',
  'emacs',
  'file',
  'flex',
  'g++',
  'g++-14',
  'gcc',
  'gcc-14',
  'gdb',
  'git',
  'gnupg',
  'gnupg-agent',
  'graphviz',
  'htop',
  'iputils-ping',
  'iputils-tracepath',
  'irssi',
  'jq',
  'less',
  'libdb-dev',
  'libpq-dev',
  'llvm',
  'lsb-release',
  'lsof',
  'make',
  'man-db',
  'mercurial',
  'moreutils',
  'mosh',
  'nano',
  'ncdu',
  'net-tools',
  'netcat-openbsd',
  'nodejs',
  'npm',
  'openssh-server',
  'perl',
  'pkg-config',
  'postgresql-client',
  'protobuf-compiler',
  'ripgrep',
  'ruby',
  'silversearcher-ag',
  'socat',
  'software-properties-common',
  'strace',
  'subversion',
  'sudo',
  'tcpdump',
  'telnet',
  'tmux',
  'unzip',
  'vim',
  'wget',
  'xsltproc ',
  'zip',
  'zsh'
]
